- components/admin/layout/Header.js
- components/admin/layout/header/HeaderDropdownDashboards.js
Task: https://www.pivotaltracker.com/story/show/152853023
> Adds dashboards submenu

- components/admin/resources/form/constants.js
- components/admin/resources/form/steps/Step1.js
Task: https://www.pivotaltracker.com/story/show/152634733
> Adds type field to resource form

- components/datasets/form/constants.js
- components/datasets/form/steps/Step1.js
Task: https://www.pivotaltracker.com/story/show/152954987
> Brings back preproduction option for datasets

- index.js
- pages/admin/Data.js
- pages/admin/MyPREP.js
Task: https://www.pivotaltracker.com/story/show/153563857
Part of: https://github.com/resource-watch/prep-app/pull/112
> Sets token session

- components/admin/layout/Header.js
- components/admin/layout/Layout.js
- components/admin/layout/Page.js
- components/app/layout/Header.js
- components/app/layout/Layout.js
- components/app/layout/header/HeaderUser.js
- pages/app/Home.js
- pages/app/Insights.js
- pages/app/Pulse.js
This PR mimics https://github.com/resource-watch/resource-watch/pull/475/files#diff-290394fa5905cf45e9a02db584f4a17d to be more consistent through apps.
@mbarrenechea I mention you just to notify this has been implemented.
> Better user management in app/admin

- components/admin/layers/form/steps/Step1.js
- components/datasets/form/DatasetsForm.js
- components/datasets/form/constants.js
- components/datasets/form/steps/Step1.js
Involved tasks:
https://www.pivotaltracker.com/story/show/153563823
https://www.pivotaltracker.com/story/show/153563774
> Changes some form params

- services/UserService.js
Task: https://www.pivotaltracker.com/story/show/154128825
> fixes logout

- components/app/myprep/profiles/form/ProfilesForm.js
- components/form/FileImage.js
- components/form/Navigation.js
> Profile: change picture, save new data and relogin each time you save

- components/admin/partners/form/PartnersForm.js
- components/admin/partners/form/constants.js
- components/admin/partners/form/steps/Step1.js
Part of: https://www.pivotaltracker.com/story/show/154134534
> Adds new partners categories

- components/ui/MainNav.js
This PR removes Link to avoid having a 404 before getting to the other app. It also removes Create from the links exposed
> Header: remove unnecessary links

- components/areas/AreaActionsTooltip.js
- components/areas/AreaCard.js
- components/areas/AreasForm.js
- components/areas/AreasList.js
- components/modal/AreaSubscriptionModal.js
- pages/admin/MyPREPDetail.js
- redactions/common.js
- services/DatasetService.js
- services/UserService.js
This PR adds: 
- Areas form, list and list item
- Subscription form
> Areas of interest

- css/_settings.scss
- css/components/widgets/widget_editor.scss
Task: https://www.pivotaltracker.com/story/show/154278690
> Adds Widget Editor styles

- css/components/ui/header-dropdown.scss
> Align header menu dropdown with prep app

- components/dashboards/related-dashboards/related-dashboards-component.js
- components/dashboards/wysiwyg/insight-block/insight-block-component.js
- components/dashboards/wysiwyg/tool-block/tool-block-component.js
- components/layout/Layout.js
- components/partners/PartnersSlider.js
- pages/app/DashboardsDetail.js
Pivotal task:
- https://www.pivotaltracker.com/story/show/154380383
> Partners: logos sizes

- components/widgets/form/WidgetsForm.js
https://www.pivotaltracker.com/story/show/154366816
> Widget form: datasets filtered by user and published if you are not an ADMIN

- components/admin/layout/Page.js
- components/app/layout/Page.js
- components/app/myprep/areas/pages/new.js
- components/app/myprep/dashboards/pages/new.js
- components/app/myprep/datasets/pages/new.js
- components/app/myprep/widgets/pages/new.js
- components/areas/AreasForm.js
- components/dashboards/form/DashboardsForm.js
- components/dashboards/form/steps/Step1.js
- components/dashboards/list/DashboardsList.js
- components/dashboards/related-dashboards/related-dashboards-component.js
- components/dashboards/wysiwyg/tool-block/tool-block-component.js
- components/dashboards/wysiwyg/widget-block/widget-block.js
- components/datasets/form/DatasetsForm.js
- components/datasets/list/DatasetsList.js
- components/form/Navigation.js
- components/widgets/form/WidgetsForm.js
- package-lock.json
- package.json
- utils/analytics.js
This PR adds some analytics events.
[Pivotal task](https://www.pivotaltracker.com/story/show/154358805)
> Analytics events

- components/admin/dashboards/pages/new.js
- components/app/myprep/dashboards/pages/new.js
- components/dashboards/form/DashboardsForm.js
- components/dashboards/list/DashboardsListCard.js
- components/dashboards/table/DashboardsTable.js
- components/dashboards/table/actions/DuplicateAction.js
- css/components/form/wysiwyg.scss
- pages/admin/DashboardsDetail.js
- services/WidgetsService.js
This PR adds a button for duplicating Dashboards. It will link to dashboardForm with an url param names duplicateId with the current id. It will fill the form and you will only need to save it.
https://www.pivotaltracker.com/story/show/154842380
> Duplicate dashboards

- components/widgets/list/WidgetCard.js
This PR adds a delay of 8 seconds to give the widget the possibility to render
You can't test it locally
> Export to PDF: add waitFor=8000

- components/dashboards/wysiwyg/widget-block-edition/widget-block-edition.js
Closes https://www.pivotaltracker.com/story/show/154376079
> Ensure users can only view published widgets

- components/widgets/table/WidgetsTable.js
Closes https://www.pivotaltracker.com/story/show/154883278
> Admin: Show only associated dataset widgets

- pages/app/DashboardsDetail.js
PT: https://www.pivotaltracker.com/story/show/154956689
> Implements GA in dashboard detail page

- index.js
**Part 2:**  Closes https://www.pivotaltracker.com/story/show/154367331
> Prep Manager - Fix/cross domain logout

- components/app/layout/EmbedLayout.js
- components/app/layout/Layout.js
- components/modal-container/Modal.js
- components/modal-container/ShareModal.js
- components/modal-container/WelcomeModal.jsx
- components/modal-container/modal-styles.scss
- components/modal-container/nav-styles.scss
- components/modal-container/share-url/index.js
- components/modal-container/share-url/share-url-component.js
- components/modal-container/share-url/share-url-styles.scss
- components/share-modal/index.js
- components/share-modal/share-modal-actions.js
- components/share-modal/share-modal-component.js
- components/share-modal/share-modal-reducers.js
- components/widgets/editor/ui/Legend.js
- css/_settings.scss
- css/components/app/pages/dashboards.scss
- package.json
- pages/app/DashboardsDetail.js
- pages/app/embed/EmbedDashboard.js
- routes.js
- store.js
- yarn.lock
PT: https://www.pivotaltracker.com/story/show/154726779
> Dashboards embeds

- components/app/myprep/datasets/pages/my-prep-datasets/dataset-list/dataset-list-card-component.js
- components/app/myprep/datasets/pages/my-prep-datasets/dataset-list/index.js
- components/app/myprep/datasets/pages/my-prep-datasets/index.js
- components/app/myprep/widgets/my-prep-widgets/index.js
- components/widgets/list/WidgetActionsTooltip.js
- components/widgets/list/WidgetCard.js
Closes https://www.pivotaltracker.com/story/show/154366562
**Todo:** make parallel changes in RW.
> Update edit and delete authorisations for widgets and datasets

- components/datasets/form/DatasetsForm.js
- css/components/ui/suggest.scss
- css/index.scss
**Closes**:  https://www.pivotaltracker.com/story/show/153637954
If basic user `this.props.basic`
> MyPrep: Add button prompt for basic users to suggest datasets

- components/app/myprep/datasets/pages/my-prep-datasets/dataset-list/dataset-list-card-component.js
- components/datasets/common/DatasetsRelatedContent.js
- components/datasets/list/DatasetsListCard.js
This PR solves 2 bugs:
- Dataset name didn't appear in DatasetCards
- Links to edition only available for admin or owners
https://www.pivotaltracker.com/story/show/155001821
> Myprep dataset name

- components/app/common/section-intro/index.js
- css/components/app/common/article.scss
- css/components/app/common/section-intro.scss
- css/components/app/pages/widget-detail.scss
- css/index.scss
- css/layouts/_page.scss
- pages/app/widget-detail/index.js
- pages/app/widget-detail/widget-detail-actions.js
- pages/app/widget-detail/widget-detail-component.js
- pages/app/widget-detail/widget-detail-default-state.js
- pages/app/widget-detail/widget-detail-reducers.js
- pages/app/widget-detail/widget-detail.js
- routes.js
- store.js
**Closes:** https://www.pivotaltracker.com/story/show/155435249
This is the initial page based on existing widget component organisation.
> Add widget details page

- services/UserService.js
Closes https://www.pivotaltracker.com/story/show/155200713
> My prep: Fix upload of user profile image

- components/app/layout/header/HeaderUser.js
Reverts resource-watch/prep-manager#74
> Revert "Fix user login to the prep application for api"

- components/admin/metadata/form/MetadataForm.js
- components/admin/metadata/form/constants.js
- components/admin/metadata/form/steps/Step1.js
Closes https://www.pivotaltracker.com/story/show/155906599
**Note:** identified additional bugs as part of this work (please review):
https://www.pivotaltracker.com/story/show/156128331
https://www.pivotaltracker.com/story/show/156124601
> Add dataset metadata columns section to edit column alias

- components/dashboards/list/DashboardsList.js
Closes https://www.pivotaltracker.com/story/show/156121115
> MyPrep: Fix dashboards search

- components/admin/metadata/form/MetadataForm.js
- components/admin/metadata/form/steps/Step1.js
- components/app/myprep/datasets/pages/show.js
Closes https://www.pivotaltracker.com/story/show/156128331
> Ensure only role admin users can update metadata
